
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybTY4QqJgLNwBIKkRdcjUCpeVRgAGrcg',
    appId: '1:457590061929:web:c120894f8dead54d711bf8',
    messagingSenderId: '457590061929',
    projectId: 'bitemates-98f26',
    authDomain: 'bitemates-98f26.firebaseapp.com',
    storageBucket: 'bitemates-98f26.firebasestorage.app',
    measurementId: 'G-LZFBF5VFY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR5prlnJv9FU8YTGBXaMQGVi6rH5teeEk',
    appId: '1:457590061929:android:9e6bcbc5e2cc013d711bf8',
    messagingSenderId: '457590061929',
    projectId: 'bitemates-98f26',
    storageBucket: 'bitemates-98f26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxls5vvvR56aBX7AcoFrmjoTFq-Jfr8U',
    appId: '1:457590061929:ios:15594128ee9322db711bf8',
    messagingSenderId: '457590061929',
    projectId: 'bitemates-98f26',
    storageBucket: 'bitemates-98f26.firebasestorage.app',
    iosBundleId: 'com.example.bitemates',
  );
}
